### PR TITLE
add support for es6 super()

### PR DESCRIPTION
**Pull request by sterlinghw**
Hoping to fix: gotwarlost/istanbul#414

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks.

**Comment by sterlinghw** [comment]
Thanks for merging! I noticed that the last release was about 7 months ago. Would you mind publishing to npm so we can fix `istanbul` as well?

**Comment by michaelficarra** [comment]
I'd prefer if @Constellation made a release, but if we can't get in touch with him in a reasonable amount of time, I will do it. Ping me again if this becomes urgent.

**Comment by sterlinghw** [comment]
Any update on publishing?

**Comment by michaelficarra** [comment]
Published `1.7.0`: https://www.npmjs.com/package/escodegen

**Comment by sterlinghw** [comment]
Thanks!

**Pull request merged**
