### PR TITLE
Update to nodeJS@6

### PR DESCRIPTION
**Pull request by sanex3339**
Update to nodeJS@6. This is intermediate update because the goal is to update to the nodeJS@10

### CODE REVIEW

**Comment by sanex3339** [comment]
@michaelficarra take a look please.

**Comment by sanex3339** [comment]
I just cherry-picked this commit from https://github.com/estools/escodegen/pull/412

**Comment by sanex3339** [comment]
I'll reopen another one with single commit history

**Comment by bakkot** [comment]
@sanex3339 For future reference, you can just force-push down to a single commit; there's no reason to open a new PR.

**Pull request closed without merging**
