### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Y--**
Especially `estraverse` so it support latest ES6 keywords

### CODE REVIEW

**Comment by NicolasPelletier** [comment]
Ping ! This has been opened for a while. Do we really care about the old node versions ( which seem to be what fails on Travis ) ? 

What is the plan for escodegen regarding new features of ES ? The organization supporting this repository is called ECMAScript Tooling after all.

**Comment by michaelficarra** [comment]
@Y-- if you rebase, CI should pass and I can merge this.

**Comment by Y--** [comment]
Rebased it, thanks!

**Comment by NicolasPelletier** [comment]
Fantastic. Thank you very much @michaelficarra and @Y--. 

When can we expect the next release ? It's been a year since 1.8.1.

I am pushing this because our developers are getting antsy to use ES6 features and get frustrated of not being able to. We can always use a git url, but it is so much cleaner to use a released version.

Thanks again.

**Comment by michaelficarra** [comment]
@NicolasPelletier Published v1.9.0.

**Comment by NicolasPelletier** [comment]
@michaelficarra : Fantastic again. Developers here are bowing to me now because I pushed the issue, but you are the unsung hero. Thanks.

**Comment by michaelficarra** [comment]
@NicolasPelletier Happy to help.

**Pull request merged**
