### PR TITLE
add support for optional catch binding

### LINKED ISSUE #382: Support optional catch binding
Support this [Stage 4 proposal](https://github.com/tc39/proposal-optional-catch-binding) to allow omission of `catch` variable in cases where the error is unused:
```javascript
try {
  // ...
} catch {
  // ...
}
```

See [Why?](https://github.com/tc39/proposal-optional-catch-binding/issues/2) for justification and more details.

This has already been implemented in [v8 6.6](https://v8.dev/blog/v8-release-66) and is available in recent versions of Chrome and in [Node.js 10](https://github.com/nodejs/node/blob/4d58c08865d7c996bb8cfbe15793443fd425410f/lib/assert.js#L138).

### To reproduce
```javascript
escodegen.generate({
  type: 'TryStatement',
  block: {
    type: 'BlockStatement',
    body: []
  },
  handler: {
    type: 'CatchClause',
    param: null,
    body: {
      type: 'BlockStatement',
      body: []
    }
  },
  finalizer: null
})
```

### Output
```
/Users/ehdens/misc-oss/escodegen/escodegen.js:2446
        type = expr.type || Syntax.Property;
                    ^

TypeError: Cannot read property 'type' of null
    at CodeGenerator.generateExpression (/Users/ehdens/misc-oss/escodegen/escodegen.js:2446:21)
    at /Users/ehdens/misc-oss/escodegen/escodegen.js:1181:26
    at withIndent (/Users/ehdens/misc-oss/escodegen/escodegen.js:574:9)
    at CodeGenerator.CatchClause (/Users/ehdens/misc-oss/escodegen/escodegen.js:1176:13)
    at CodeGenerator.generateStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:2465:33)
    at CodeGenerator.TryStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:1526:52)
    at CodeGenerator.generateStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:2465:33)
    at generateInternal (/Users/ehdens/misc-oss/escodegen/escodegen.js:2486:28)
    at Object.generate (/Users/ehdens/misc-oss/escodegen/escodegen.js:2554:18)
    at Object.<anonymous> (/Users/ehdens/misc-oss/escodegen/demo.js:3:24)
```

### Expected Output
```javascript
try {
} catch {
}
```

### PR DESCRIPTION
**Pull request by cixel**
Fixes #382.

Tests rely on [esprima 1953](https://github.com/jquery/esprima/issues/1953) or they will throw early:
```
  1) general test try statement:
     AssertionError: expected [Function] to not throw an error but 'Error: Line 1: Unexpected token {' was thrown
      at testIdentity (test/test.js:14946:23)
      at runTest (test/test.js:14974:9)
      at test/test.js:14983:17
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (test/test.js:14981:41)
```
This PR can hibernate until there's progress on esprima's end, and until esprima dependency version bumps to 4.x+.

### CODE REVIEW

**Comment by sanex3339** [comment]
Any update on this?

**Comment by sanex3339** [comment]
@cixel

**Comment by sanex3339** [comment]
https://github.com/estools/escodegen/pull/398 is merged
Can you update this PR?

**Comment by sanex3339** [comment]
If here will be no actions in the next few hours, i'll recreate this PR with updated `esprima` dependency.

**Comment by cixel** [comment]
Sorry, I've been away. It may be simplest for you to recreate the PR, I haven't touched this stuff in a while.

**Comment by sanex3339** [comment]
Yep. I already did
https://github.com/estools/escodegen/pull/403

**Comment by cixel** [comment]
Good stuff. Thanks!

**Pull request closed without merging**
