### PR TITLE
Added simple support for MetaProperty

### PR DESCRIPTION
**Pull request by steve-gray**
Support for MetaProperty node type. A very straighforward variant of the MemberExpression, with little work required. This lets syntax such as new.target get parsed in ES6 code.

### CODE REVIEW

**Comment by Constellation** [comment]
Looks nice. Could you add a test?

**Comment by steve-gray** [comment]
Would you recommend adding it to Harmony.js?

**Comment by steve-gray** [comment]
Had to add tests to a new harmony-2.5.js file that works against esprima ^2.5 due to differences in behaviour that invalidate other tests, and I didn't fancy going through and doing all the changes and potentially invalidating tests for unrelated features.

**Comment by Constellation** [comment]
Ah. OK. Looks fine.

**Comment by Constellation** [comment]
Thanks!!!

**Comment by steve-gray** [comment]
Any chance of pushing a release so I can pursue this through with the Istanbul team for a downstream change to add this support there?

**Pull request merged**
