### PR TITLE
fixes #358: correctly codegen AssignmentPattern in ObjectPattern

### LINKED ISSUE #358: Property issue in ObjectPattern
Hello I've stumbled in this code example:
```
let { test:myvar = "default" }= { test: "aValue" };
```
Escodegen outputs the following code from Esprima AST:
```
let {
    myvar = 'default': myvar = 'default'
} = { test: 'aValue' };
```
Which is obviously wrong.
Sample code to reproduce:
```
var es_parse = require('esprima').parse;
var esgenerate = require('escodegen').generate
var code = 'let { test:myvar = "default" }= { test: "aValue" };';
var ast = es_parse(code);
console.log(esgenerate(ast));
```

Thanks!

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #358. Closes #359. /cc @wisec

### CODE REVIEW

**Comment by wisec** [comment]
Thank!

**Comment by papandreou** [comment]
I just ran into this bug (https://github.com/assetgraph/assetgraph-builder/issues/549). Any chance of a new release with this fix?

**Comment by michaelficarra** [comment]
@papandreou Yes, I've been meaning to do it for a while. Thanks for the reminder.

**Comment by michaelficarra** [comment]
@papandreou Version 1.9.1 published.

**Comment by papandreou** [comment]
@michaelficarra, thanks -- also for the ping :)

**Pull request merged**
