### PR TITLE
Updating jQuery test deps to prevent false positive security scans

### PR DESCRIPTION
**Pull request by ndewing**
* Removing jQuery 1.6.4 and 1.7.1, and jQuery mobile 1.0.
* Added jQuery 3.4.1.
* Added jQuery mobile 1.4.5.
* Updated test/identity.js

## Motivation and Context
Updates jQuery to a supported version of jQuery that is safer and won't cause security scanners to flag the library as vulnerable.

## How Has This Been Tested
I've run the build and tests to ensure nothing broke.

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'm not interested in removing these test files. Maybe you can just change the test in an inconsequential way that will cause the security scanners to fail to detect the file.

**Comment by clarkead** [comment]
I'm confused.  This PR doesn't remove any test files it just updates them to supported versions without any vulnerabilities.  This seems to be the "change the test in an inconsequential  way" that will cause the security scanners to pass.  I'm having this same issue and while it seems to be a low impact issue every team that runs a security scan will have this flagged and have to investigate it.  What is the technical merit for not including this?  Maybe I'm missing something.

**Comment by ndewing** [comment]
@michaelficarra Updating jQuery in the test suite is simply low hanging fruit that saves teams time when working composition analysis reports. This seems to be a quick win that can be bundled into the next release or am I missing something?

**Comment by michaelficarra** [comment]
@clarkead This is certainly not an inconsequential change. I'm sure modern jQuery is nothing like old jQuery. In case you're not aware, jQuery is not *run* by the test suite, it *is* the test. I do not have confidence that a modern jQuery will exercise the code generator in the same ways that the old one does. An actual minor change would be whitespace or string escaping or something.

@ndewing The test files are not distributed with the release. This will only affect security scans of clones of this repo, not installations of the node module.

**Comment by ndewing** [comment]
Thanks for the clairification @michaelficarra, you are correct the tests aren't distributed with the release or Escodegen. Dug more into the issue I'm seeing, and found old Escodegen releases bundled with an agent. Will close #399 and #400.

**Pull request closed without merging**
