### PR TITLE
Fix #376: support dynamic import

### LINKED ISSUE #376: dynamic imports are not supported
esprima now supports dynamic imports (node will have type = 'Import')
However, parsing the tree and generating it with escodegen results in a crash:

```
TypeError: this[type] is not a function
    at CodeGenerator.generateExpression (/Users/dom/Developer/web/minify-lit-html-loader-master/node_modules/escodegen/escodegen.js:2453:28)
```
crash happend while type = 'Import'.

### PR DESCRIPTION
**Pull request by seasonli**
support dynamic import

### CODE REVIEW

**Comment by papandreou** [comment]
I'd really like this to land. Implemented a few tests here: https://github.com/seasonli/escodegen/pull/1

**Comment by papandreou** [comment]
@seasonli, would be great to get this in. Mind having a look at the tests I opened a PR for in your fork? https://github.com/seasonli/escodegen/pull/1

**Comment by papandreou** [comment]
Since this doesn't seem to be going anywhere, I opened #395 with those tests included.

**Comment by michaelficarra** [comment]
Fixed by #395.

**Pull request closed without merging**
