### PR TITLE
Exponentiation operator

### PR DESCRIPTION
**Pull request by sanex3339**
Fixed exponentiation operator precedence, like described here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

Fixed https://github.com/estools/escodegen/issues/406
Fixed https://github.com/javascript-obfuscator/javascript-obfuscator/issues/534

### CODE REVIEW

**Comment by sanex3339** [comment]
@michaelficarra I will be happy if you will review it

**Comment by pawelzwronek** [comment]
It would be great to include this PR in next release.

**Comment by michaelficarra** [comment]
I would like to see tests for forced grouping of unary operations on the LHS. For example, we shouldn't render `(-1) ** 0` as `-1 ** 0`.

**Comment by sanex3339** [comment]
But currently in `master` it rendered `(-1) * 0` as `-1 * 0`

**Comment by michaelficarra** [comment]
@sanex3339 the `*` and `**` operators have different grammars. the LHS of `**` is a higher precedence position than the RHS. For `*`

**Comment by sanex3339** [comment]
Hmm. Will try to fix

**Comment by sanex3339** [comment]
@michaelficarra I have no idea what i'm doing, but looks like now new test cases for LHS expression are passing

**Comment by michaelficarra** [comment]
@sanex3339 I pushed up another commit. Please review.

**Comment by sanex3339** [comment]
@michaelficarra Looks good, thank you!

**Comment by michaelficarra** [comment]
@sanex3339 Published version `1.14.0`.

**Pull request merged**
