### PR TITLE
Support RestElement

### LINKED ISSUE #225: Support RestElement
https://github.com/estree/estree/blob/master/es6.md#restelement

### PR DESCRIPTION
**Pull request by ef4**
Closes #225.

### CODE REVIEW

**Comment by Constellation** [comment]
LGTM

**Comment by Constellation** [comment]
After seeing the test is pased, i'll merge it.

**Comment by Constellation** [comment]
Thank you!

**Comment by ArtemGovorov** [comment]
Shouldn't it be `generatePattern` as opposed to `generateIdentifier `? Spec allows the argument to be a pattern https://github.com/estree/estree/blob/master/es6.md#restelement

**Comment by ef4** [comment]
@ArtemGovorov I see you're correct, I will submit another PR that expands coverage to all patterns.

**Comment by michaelficarra** [comment]
That's a spec bug. I will submit an estree issue.

**Comment by ef4** [comment]
If it's a bug, it seems to already be implemented in multiple places. esprima supports it, and babel (uses acorn?) supports it too.

**Comment by michaelficarra** [comment]
See my edit above. I made a mistake.

**Pull request merged**
