### PR TITLE
Add realJson option. Closes #304

### LINKED ISSUE #304: Generate real json
escodegen with options `{format:{json:true}}` generates values in json style.
i want generate json keys too.

like this: `{"block":"block1"}`
not like this: `{block:"block1"}`

### PR DESCRIPTION
**Pull request by a-x-**

### CODE REVIEW

**Comment by Noiwex** [comment]
rip project maintainer

**Comment by Constellation** [comment]
I think we should change the `json` behavior to this one, could you update the patch?
/cc @michaelficarra

**Comment by michaelficarra** [comment]
Agreed.

**Comment by michaelficarra** [comment]
I'm going to close this PR, as it doesn't make much progress toward solving #304.

* We don't need a new option. The existing `json` option should be sufficient.
* We can't just naïvely wrap the key in quotes. What if it contains quotes already?
* There's no tests.

**Pull request closed without merging**
