### PR TITLE
Fix #328. Render as AssignmentPattern only when property name matches with value name

### LINKED ISSUE #328: Incorrect generation of destructuring assignment with rename and default
```
const {generate} = require('escodegen');
const {parse} = require('esprima');

generate(parse('const {foo: bar = baz} = quux')) === `const {
  bar = baz: bar = baz
} = quux;`
```

### PR DESCRIPTION
**Pull request by quarterto**

### CODE REVIEW

**Comment by michaelficarra** [comment]
@quarterto I think you meant to just include 28a4da0a5f58e7f51a6e3ba7000d92b198b98bd9. The other commits are unrelated to the PR title or linked issue, and I wouldn't want to accept them.

**Comment by t2ym** [comment]
@quarterto I created [t2ym/escodegen#fix-328](https://github.com/t2ym/escodegen/commits/fix-328) branch so that you can create a pull request including only the targeted commit for Fix #328.

**Comment by michaelficarra** [comment]
@quarterto: https://github.com/estools/escodegen/compare/master...t2ym:fix-328

I would like to see some tests with it, please.

**Comment by t2ym** [comment]
@quarterto I understand your concern but my fork is a custom version for my own project and not intended for merging into the main repository.  The status that the project is working well is sufficient validation of the fix for the project.  To meet the needs of the project, the fork may distract from the the main repository in the future.  So if you want dedicated tests on the fix, I am afraid you can create your own fork to implement them.

**Pull request closed without merging**
