### PR TITLE
2.0.0: Optional catch binding support, removed CLI scripts

### PR DESCRIPTION
**Pull request by sanex3339**
2.0.0: 
- Optional catch binding support
- Removed CLI scripts
- Increased minimal required node.js version to 8+
- updated gulp to 4+ version to support development on node.js 12+
- updated gulpfile.js

This is breaking PR, so, updated version to 2.0.0

### CODE REVIEW

**Comment by sanex3339** [comment]
@michaelficarra need your review

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
@michaelficarra ping

**Comment by sanex3339** [comment]
@michaelficarra ping

**Comment by michaelficarra** [comment]
@sanex3339 I don't like that this PR includes so many unrelated changes. I would accept a PR that just adds the optional catch binding support. The remaining changes don't seem worth it to me, but we can have conversation about that in separate PRs. Closing this, but feel free to open separate PRs for these separate features.

**Comment by sanex3339** [comment]
Optional catch binding is not supported by `esprima`, so, i will added `espree` that support it.
But `espree` does not support `node@4`.
So i updated to `node@8` and fixed compilation on current LTS node 12+.

**Comment by sanex3339** [comment]
Will recreate this PR using `acorn`

**Comment by sanex3339** [comment]
https://github.com/estools/escodegen/pull/405

**Pull request closed without merging**
